# Render Configuration File for Next.js Application
# Docs: https://render.com/docs/deploy-next-js

services:
  - type: web
    name: coworking-platform
    env: node
    region: singapore  # Choose the region closest to your users
    plan: free  # or 'standard' for production
    
    # Build configuration
    buildCommand: |
      # Install dependencies
      npm ci --ignore-scripts
      
      # Build the application
      npm run build
    
    # Start command for the application
    startCommand: npm start
    
    # Auto-deploy from Git
    autoDeploy: true
    
    # Environment variables
    envVars:
      # Required for Next.js
      - key: NODE_ENV
        value: production
        
      # Database configuration
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
          
      # NextAuth configuration
      - key: NEXTAUTH_URL
        generateValue: true
        pattern: "https://{{name}}.onrender.com"
      - key: NEXTAUTH_SECRET
        generateValue: true
        
      # Optional: Add your Google OAuth credentials if using Google Auth
      # - key: GOOGLE_CLIENT_ID
      #   sync: false
      # - key: GOOGLE_CLIENT_SECRET
      #   sync: false
      
      # Optional: Add your GitHub OAuth credentials if using GitHub Auth
      # - key: GITHUB_ID
      #   sync: false
      # - key: GITHUB_SECRET
      #   sync: false
      
      # Security headers (handled by Next.js)
      - key: SECURITY_HEADERS
        value: "true"
        
      # Performance optimizations
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.x  # Using LTS version for better stability
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
      
      # Package manager configuration
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: HUSKY
        value: "0"
      
      # Next.js configuration
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_SHARP_PATH
        value: "/usr/local/lib/node_modules/sharp"
      
      # Application URLs
      - key: NEXTAUTH_URL
        value: https://coworking-platform.onrender.com 
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        value: https://coworking-platform.onrender.com
        sync: false
      
      # Authentication
      - key: NEXTAUTH_SECRET
        value: s+JYLbbzVaJoBeaQawj42O1QGAAxMR8VL/W0oee9IEo=
        sync: false
      
      # Database
      - key: MONGODB_URI
        value: mongodb+srv://grabatassnim:pvsd8mdXyqXKHgiT@cluster0.av4bvfl.mongodb.net/coworking-platform?retryWrites=true&w=majority
        sync: false
    
    # Build settings
    build:
      useCache: true
      cacheVersion: 1  # Increment to bust the cache when needed
    
    # Health check configuration
    healthCheckPath: /api/health
    
    # Plan and resources
    plan: free
    
    # Auto-deploy settings
    autoDeploy: true
    
    # Build environment settings
    buildEnvironment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=4096
      - NPM_CONFIG_PRODUCTION=false
      - NEXT_TELEMETRY_DISABLED=1
