# Render Configuration File for Next.js Application
# Docs: https://render.com/docs/deploy-next-js

services:
  - type: web
    name: coworking-platform
    env: node
    region: singapore  # Choose the region closest to your users
    plan: free  # or 'standard' for production
    
    # Build configuration
    buildCommand: |
      # Set Node.js version
      echo "Setting Node.js version to 20..."
      nvm install 20
      nvm use 20
      
      # Install Node.js dependencies with legacy peer deps
      echo "Installing dependencies..."
      npm config set legacy-peer-deps true
      npm ci --prefer-offline --no-audit --progress=false
      
      # Install build dependencies
      echo "Installing build dependencies..."
      sudo apt-get update
      sudo apt-get install -y build-essential python3
      
      # Set C++ standard to 20 for native modules
      export CXXFLAGS="--std=c++20"
      export npm_config_build_from_source=true
      
      # Install Prisma and generate client
      echo "Setting up Prisma..."
      npx prisma generate
      
      # Build the application
      echo "Building application..."
      npm run build
      
      # Create standalone output
      echo "Preparing standalone output..."
      mkdir -p .next/standalone-temp
      cp -r .next/standalone/. .next/standalone-temp/
      mkdir -p .next/standalone-temp/.next
      cp -r .next/static .next/standalone-temp/.next/
      cp -r .next/server .next/standalone-temp/.next/
      cp -r public .next/standalone-temp/
      cp next.config.js .next/standalone-temp/
      rm -rf .next/standalone
      mv .next/standalone-temp .next/standalone
      
      # Make server.js executable
      chmod +x .next/standalone/server.js
      
      echo "Build completed successfully!"
    
    # Start command for the application
    startCommand: >-
      echo "Starting application..."
      cd .next/standalone
      NODE_ENV=production PORT=$PORT node server.js
    
    # Health check path
    healthCheckPath: /api/health
    
    # Environment variables
    envVars:
      # Required variables
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max_old_space_size=2048
      
      # Next.js specific
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_SHARP_PATH
        value: "./node_modules/sharp"
      - key: NEXT_PUBLIC_APP_URL
        value: https://your-render-app-url.onrender.com  # Update this with your actual URL
      
      # Prisma configuration
      - key: PRISMA_QUERY_ENGINE_BINARY
        value: "./node_modules/prisma/query-engine"
      - key: PRISMA_SCHEMA_ENGINE_BINARY
        value: "./node_modules/prisma/schema-prisma"
      - key: PRISMA_CLI_QUERY_ENGINE_TYPE
        value: "binary"
      
      # Build optimization
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "1"
      - key: SKIP_ENV_VALIDATION
        value: "1"
      - key: CI
        value: "false"
    
    # Build environment variables
    build:
      NODE_ENV: production
      NODE_OPTIONS: --max_old_space_size=4096
      NPM_CONFIG_PRODUCTION: "false"
      NPM_CONFIG_LEGACY_PEER_DEPS: "true"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      PRISMA_CLI_QUERY_ENGINE_TYPE: "binary"
      SKIP_ENV_VALIDATION: "1"
      CI: "false"
    
    # Auto-deploy settings
    autoDeploy: true
    
    # Post-deploy script (runs after deployment)
    postdeploy: |
      echo "Running post-deployment tasks..."
      # Generate Prisma client if needed
      npx prisma generate
      # Run database migrations
      npx prisma migrate deploy
      # Build the application
      npm run build
      echo "Post-deployment tasks completed!"
    
    # Build cache settings
    buildCachePolicy: "DEFAULT"
    
    # Build timeout (in minutes)
    buildTimeout: 30
    
    # Auto-deploy from Git
    autoDeploy: true
    
    # Environment variables
    envVars:
      # Required for Next.js
      - key: NODE_ENV
        value: production
        
      # Database configuration
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb-atlas
          property: connectionString
          
      # NextAuth configuration
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_URL_INTERNAL
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false
        
      # Optional: Add your Google OAuth credentials if using Google Auth
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
        
      # Optional: Add your GitHub OAuth credentials if using GitHub Auth
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
        
      # Security headers (handled by Next.js)
      - key: SECURITY_HEADERS
        value: "true"
        
      # Performance optimizations
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.x  # Using LTS version for better stability
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
      
      # Package manager configuration
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: HUSKY
        value: "0"
      
      # Next.js configuration
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_SHARP_PATH
        value: "/usr/local/lib/node_modules/sharp"
      
      # Application URLs
      - key: NEXTAUTH_URL
        value: https://coworking-platform.onrender.com 
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        value: https://coworking-platform.onrender.com
        sync: false
      
      # Authentication
      - key: NEXTAUTH_SECRET
        value: s+JYLbbzVaJoBeaQawj42O1QGAAxMR8VL/W0oee9IEo=
        sync: false
      
      # Database
      - key: MONGODB_URI
        value: mongodb+srv://grabatassnim:pvsd8mdXyqXKHgiT@cluster0.av4bvfl.mongodb.net/coworking-platform?retryWrites=true&w=majority
        sync: false
    
    # Build settings
    build:
      useCache: true
      cacheVersion: 1  # Increment to bust the cache when needed
    
    # Health check configuration
    healthCheckPath: /api/health
    
    # Plan and resources
    plan: free
    
    # Auto-deploy settings
    autoDeploy: true
    
    # Build environment settings
    buildEnvironment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=4096
      - NPM_CONFIG_PRODUCTION=false
      - NEXT_TELEMETRY_DISABLED=1
