# Render Configuration File for Next.js Application
# Docs: https://render.com/docs/deploy-next-js

services:
  - type: web
    name: coworking-platform
    env: node
    region: singapore  # Choose the region closest to your users
    plan: free  # or 'standard' for production
    
    # Build configuration
    buildCommand: |
      # Install dependencies
      npm ci
      
      # Build the application
      npm run build
      
      # Create necessary directories
      mkdir -p .next/standalone/.next
      
      # Copy required files for standalone mode
      cp -r .next/static .next/standalone/.next/
      cp -r public .next/standalone/
      cp next.config.js .next/standalone/
      
      echo "Build completed successfully"
    
    # Start command for the application
    startCommand: >-
      if [ -f ".next/standalone/server.js" ]; then
        echo "Starting in standalone mode"
        cd .next/standalone && NODE_ENV=production node server.js
      else
        echo "Starting in normal mode"
        NODE_ENV=production npm start
      fi
    
    # Health check path
    healthCheckPath: /api/health
    
    # Set the port
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max_old_space_size=1024
    
    # Auto-deploy from Git
    autoDeploy: true
    
    # Environment variables
    envVars:
      # Required for Next.js
      - key: NODE_ENV
        value: production
        
      # Database configuration
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb-atlas
          property: connectionString
          
      # NextAuth configuration
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_URL_INTERNAL
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false
        
      # Optional: Add your Google OAuth credentials if using Google Auth
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
        
      # Optional: Add your GitHub OAuth credentials if using GitHub Auth
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
        
      # Security headers (handled by Next.js)
      - key: SECURITY_HEADERS
        value: "true"
        
      # Performance optimizations
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.x  # Using LTS version for better stability
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
      
      # Package manager configuration
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: HUSKY
        value: "0"
      
      # Next.js configuration
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_SHARP_PATH
        value: "/usr/local/lib/node_modules/sharp"
      
      # Application URLs
      - key: NEXTAUTH_URL
        value: https://coworking-platform.onrender.com 
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        value: https://coworking-platform.onrender.com
        sync: false
      
      # Authentication
      - key: NEXTAUTH_SECRET
        value: s+JYLbbzVaJoBeaQawj42O1QGAAxMR8VL/W0oee9IEo=
        sync: false
      
      # Database
      - key: MONGODB_URI
        value: mongodb+srv://grabatassnim:pvsd8mdXyqXKHgiT@cluster0.av4bvfl.mongodb.net/coworking-platform?retryWrites=true&w=majority
        sync: false
    
    # Build settings
    build:
      useCache: true
      cacheVersion: 1  # Increment to bust the cache when needed
    
    # Health check configuration
    healthCheckPath: /api/health
    
    # Plan and resources
    plan: free
    
    # Auto-deploy settings
    autoDeploy: true
    
    # Build environment settings
    buildEnvironment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=4096
      - NPM_CONFIG_PRODUCTION=false
      - NEXT_TELEMETRY_DISABLED=1
