# Render Configuration File
# Docs: https://render.com/docs/deploy-next-js#deploy-nextjs-with-render

services:
  - type: web
    name: coworking-platform
    env: node
    region: singapore  # Choose the region closest to your users
    
    # Build configuration
    buildCommand: |
      # Install dependencies (ignore scripts to avoid husky issues)
      npm ci --ignore-scripts
      
      # Install husky only if not in CI
      if [ -z "$CI" ]; then
        npx husky install
      fi
      
      # Build the application
      npm run build
    
    # Start command for the application
    startCommand: npm start
    
    # Static site configuration
    staticPublishPath: ./out
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    
    # Security headers for static exports
    headers:
      - key: X-Content-Type-Options
        value: nosniff
      - key: X-Frame-Options
        value: DENY
      - key: X-XSS-Protection
        value: 1; mode=block
      - key: Content-Security-Policy
        value: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;
    
    # Environment variables
    envVars:
      # CI/CD configuration
      - key: CI
        value: "true"
      
      # Node.js configuration
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.x  # Using LTS version for better stability
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
      
      # Package manager configuration
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: HUSKY
        value: "0"
      
      # Next.js configuration
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_SHARP_PATH
        value: "/usr/local/lib/node_modules/sharp"
      
      # Application URLs
      - key: NEXTAUTH_URL
        value: https://coworking-platform.onrender.com 
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        value: https://coworking-platform.onrender.com
        sync: false
      
      # Authentication
      - key: NEXTAUTH_SECRET
        value: s+JYLbbzVaJoBeaQawj42O1QGAAxMR8VL/W0oee9IEo=
        sync: false
      
      # Database
      - key: MONGODB_URI
        value: mongodb+srv://grabatassnim:pvsd8mdXyqXKHgiT@cluster0.av4bvfl.mongodb.net/coworking-platform?retryWrites=true&w=majority
        sync: false
    
    # Build settings
    build:
      useCache: true
      cacheVersion: 1  # Increment to bust the cache when needed
    
    # Health check configuration
    healthCheckPath: /api/health
    
    # Plan and resources
    plan: free
    
    # Auto-deploy settings
    autoDeploy: true
    
    # Build environment settings
    buildEnvironment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=4096
      - NPM_CONFIG_PRODUCTION=false
      - NEXT_TELEMETRY_DISABLED=1
